source 'https://github.com/T2015/REPO.git'

use_frameworks!

platform :ios, '11.0'

target 'YJAPI_Example' do
  pod 'YJAPI', :path => '../'
  pod 'JKAPI'
  
  
  target 'YJAPI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
